# Generated by Django 6.1 on 2026-08-17 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='titile',
            new_name='title',
        ),
    ]
